name: Github Release
on: 
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  MOD_FILE: "./NeoConsole.cs"

jobs:
  build-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # - name: Setup .NET 6.0
      #   uses: actions/setup-dotnet@master
      #   with:
      #     dotnet-version: 6.0.x

      # - name: Download .sml Packer
      #   run: echo "TODO"

      # - name: Pack .sml
      #   run: echo "TODO"

      - name: Parse Name / Version / Description
        run: |
          NAME=$(grep -oP 'Name => "\K[^"]+' ${{ env.CS_FILE_NAME }})
          VERSION=$(grep -oP 'Version => "\K[^"]+' ${{ env.CS_FILE_NAME }})
          DESCRIPTION=$(grep -oP 'Description => "\K[^"]+' ${{ env.CS_FILE_NAME }})
          echo "NAME=$NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
          echo $NAME $VERSION $DESCRIPTION

      # - name: Upload .sml artifact
      #   uses: actions/upload-artifact@v4
      #   with: 
      #     name: ${{ MOD_NAME  }}.sml
      #     path: ./mod.sml

  gh-release:
    runs-on: ubuntu-latest
    needs: ["build-module"]
    steps:
    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifactErrorsFailBuild: true
        artifacts: ${{ env.MOD_NAME }}.sml
        body: ${{ env.MOD_DESCRIPTION }}
        draft: true
        name: ${{ env.MOD_VERSION }}
        skipIfReleaseExists: true
        tag: v${{ env.MOD_VERSION }}
